project:
  type: website
  preview: 
    port: 4200
    host: 127.0.0.1
    browser: false

website:
  title: "HealthRADAR"
  image: "img/logo-light.png"
  favicon: "favicon.ico"
  bread-crumbs: false
  search:
    location: navbar
    type: textbox
  navbar:
    logo: "img/logo-light.png"
    left:
      - text: Home
        href: index.qmd
      - text: Browse
        href: data.qmd
      - text: Guides
        menu: 
          - text: Climate
            href: guides/climate.qmd
          - text: Modelling
            href: guides/modelling.qmd
      - text: About
        href: about.qmd
        
    pinned: true
  page-footer: "Copyright 2024, Health RADAR"
  
language: 
  search-text-placeholder: "Search"
  
format:
  html:
    theme:
      light: [flatly, style-light.scss, style-base.scss]
      #dark: [darkly, style-dark.scss, style-base.scss]
    toc: true
    mainfont: "Schibsted Grotesk"
    code-fold: true
    code-summary: "Show the code"

execute:
  freeze: auto

