project:
  type: website

website:
  title: "HealthRADAR"
  image: "img/logo-light.png"
  favicon: "favicon.ico"
  navbar:
    logo: "img/logo-light.png"
    left:
      - href: index.qmd
        text: Home
      - href: data.qmd
        text: Data 
      - href: about.qmd
        text: About
    pinned: true
  page-footer:   
    center: |
      <span class="faux-block">{{< fa brands creative-commons >}} 2024 Health RADAR </span> <br/>
      <span class="faux-block">All content licensed under [{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} Creative Commons CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)</span>

format:
  html:
    theme:
      light: [flatly, style-light.scss, style-base.scss]
      dark: [darkly, style-dark.scss, style-base.scss]
    toc: true
    mainfont: "Schibsted Grotesk"

execute:
  freeze: auto

