project:
  type: website

website:
  title: "HealthRADAR"
  image: "img/logo-light.png"
  favicon: "favicon.ico"
  navbar:
    logo: "img/logo-light.png"
    left:
      - href: index.qmd
        text: Home
      - href: datapages.qmd
        text: Data Pages
      - href: about.qmd
        text: About
    pinned: true

format:
  html:
    theme:
      light: [flatly, style-light.scss, style-base.scss]
      dark: [darkly, style-dark.scss, style-base.scss]
    toc: true

execute:
  freeze: auto

