project:
  type: website
  output-dir: "_site"
  preview: 
    port: 4200
    host: 127.0.0.1
    browser: false

website:
  title: "HealthRADAR"
  image: "radar/img/logo-light.png"
  site-url: https://uct-masha.quarto.pub/healthradar/radar/
  favicon: "radar/favicon.ico"
  bread-crumbs: false
  draft-mode: unlinked
  back-to-top-navigation: true
  google-analytics: "G-8LJCXZ1XXL"
  # announcement: 
  #   icon: info-circle
  #   dismissable: true
  #   content: "Please note that the website is currently a work in progress. We are actively updating content and features to enhance your experience. Check back soon for exciting updates! Your patience is appreciated!"
  #   type: info
  #   position: below-navbar
  search:
    location: navbar
    type: textbox
  navbar:
    logo: "radar/img/logo-light.png"
    left:
      - text: Home
        href: radar/index.qmd
      - text: Browse
        href: radar/data.qmd
      - text: About
        href: radar/about.qmd
      - text: Guides
        menu: 
          - text: Contributing to Health RADAR 
            href: radar/guides/contribution/contribution_guidance.qmd
          - text: Climate
            href: radar/guides/climate/climate.qmd
          - text: Modelling
            href: radar/guides/contribution/modelling.qmd
      - text: Updates
        href: radar/updates.qmd

    right:
      - icon: github
        href: https://github.com/uct-masha/HealthRADAR
        aria-label: RADAR GitHub
      
        
    pinned: true
  page-footer: 
          left: "&copy; Copyright 2025, Health RADAR"
          center:
            - text: About
              href: radar/about.qmd
            - text: Data Sources
              href: radar/data.qmd
          right: |
                <div style="text-align: right;">
                  <img src="/radar/img/wellcome-logo-white.png" width="100px" alt="Wellcome Logo" />
                  <div style="font-size: 1em; color: white; font-weight: 500; margin-top: 10px">Funded by Wellcome</div>
                </div>

metadata-files:
  - radar/drafts.yml
  
language: 
  search-text-placeholder: "Search"
  
format:
  html:
    theme:
      light: [flatly, radar/style-light.scss, radar/style-base.scss]
      #dark: [darkly, style-dark.scss, style-base.scss]
    toc: true
    mainfont: "Roboto"
    monofont: "Roboto Mono"
    code-fold: true
    code-summary: "Show the code"
    highlight-style: atom-one
execute:
  freeze: auto

