project:
  type: website
  output-dir: "_site"
  preview: 
    port: 4200
    host: 127.0.0.1
    browser: false

website:
  image:  "img/logo-light.png"
  site-url: https://uct-masha.quarto.pub/healthradar/radar/
  favicon: "radar/favicon.ico"
  bread-crumbs: false
  draft-mode: unlinked
  back-to-top-navigation: true
  google-analytics: "G-H03EKDS8HM"
  # announcement: 
  #   icon: info-circle
  #   dismissable: true
  #   content: "Please note that this platform is currently in beta. We are actively refining content and features as we test and improve the experience. Your feedback is welcome during this early stage."
  #   type: info
  #   position: below-navbar
  search:
    location: navbar
    type: textbox
  navbar:
    logo: "img/Health RADAR Logo Transparent.png"
    left:
      - text: Home
        href: index.qmd
      - text: Browse
        href: data.qmd
      - text: About
        href: about.qmd
      - text: Guides
        menu: 
#          - text: Contributing to Health RADAR 
#            href: guides/contribution/contribution_guidance.qmd
          - text: Climate
            href: guides/climate/climate.qmd
#          - text: Modelling
#            href: guides/contribution/modelling.qmd
#      - text: Updates
#        href: updates.qmd
      - text: Submit an Issue
        href: issues.qmd

    right:
      - icon: github
        href: https://github.com/uct-masha/HealthRADAR
        aria-label: RADAR GitHub
      
        
    pinned: true
  page-footer: 
          left: "&copy; Copyright 2025, Health RADAR"
          center:
            - text: About
              href: about.qmd
            - text: Data Sources
              href: data.qmd
          right: |
            <div>
              <img src="/img/wellcome-logo-white.png" width="100px" alt="Wellcome Logo" />
              <div style="font-size: 1em; color: white; font-weight: 500; margin-top: 10px">Funded by Wellcome</div>
            </div>
  
language: 
  search-text-placeholder: "Search"
  
format:
  html:
    theme:
      light: [flatly, style-light.scss, style-base.scss]
      #dark: [darkly, style-dark.scss, style-base.scss]
    toc: true
    mainfont: "Roboto"
    monofont: "Roboto Mono"
    code-fold: true
    code-summary: "Show the code"
    highlight-style: atom-one
execute:
  freeze: auto

comments:
  giscus: 
    repo: uct-masha/HealthRADAR
    category: Announcements
    mapping: title
    loading: lazy
    input-position: top
