project:
  type: website
  output-dir: "_site"
  preview: 
    port: 4200
    host: 127.0.0.1
    browser: false

website:
  title: "HealthRADAR"
  image: "radar/img/logo-light.png"
  site-url: https://jfunction.quarto.pub/healthradar/radar/
  favicon: "radar/favicon.ico"
  bread-crumbs: false
  draft-mode: gone
  back-to-top-navigation: true
  search:
    location: navbar
    type: textbox
  navbar:
    logo: "radar/img/logo-light.png"
    left:
      - text: Home
        href: radar/index.qmd
      - text: Browse
        href: radar/data.qmd
      - text: Guides
        menu: 
          - text: Contributing to Health RADAR 
            href: radar/guides/contribution_guidance.qmd
          - text: Climate
            href: radar/guides/climate.qmd
          - text: Modelling
            href: radar/guides/modelling.qmd
      - text: About
        href: radar/about.qmd
    right:
      - icon: github
        href: https://github.com/uct-masha/HealthRADAR
        aria-label: RADAR GitHub
      
        
    pinned: true
  page-footer: 
          left: "Copyright 2025, Health RADAR"
          center:
            - text: About
              href: radar/about.qmd
            - text: Data Sources
              href: radar/data.qmd
          right:
            - icon: github
              href: https://github.com/uct-masha/HealthRADAR
              aria-label: RADAR GitHub

metadata-files:
  - radar/drafts.yml
  
language: 
  search-text-placeholder: "Search"
  
format:
  html:
    theme:
      light: [flatly, radar/style-light.scss, radar/style-base.scss]
      #dark: [darkly, style-dark.scss, style-base.scss]
    toc: true
    mainfont: "Public Sans"
    monofont: "Source Code Pro"
    code-fold: true
    code-summary: "Show the code"
    highlight-style: atom-one
execute:
  freeze: auto

