---
title: "About the project"
back-to-top-navigation: false
page-layout: full
title-block-banner: "#EDF3F9"
title-block-banner-color: "#212529"
---

::: {.page-tabs .panel-tabset}

## The Project

One of the greatest obstacles to CSID modelling in LMIC is accessibility to operationalisable datasets. While much data may even be publicly available, it may not be known or well understood outside of the data generators, and often not in a format that is digestible and acceptable to modellers and analysts. This barrier often prohibits the inclusion of such datasets in modelling studies leading to, for example, climate data being incorporated into disease models in a superficial manner or not at all. Climate data are, however, not the only source of data that modellers need to access for CSID modelling. Other types of data include demographic, epidemiological, entomological, health system, intervention impact and cost data.

There is a need to curate these datasets into a central resource where the datasets may be viewed, explored and downloaded with an emphasis on comprehensive documentation describing and contextualising each dataset with worked examples on how to incorporate data into CSID models.

Health RADAR is a space where various stakeholders can learn about what data exist together with the context behind it. There is also information on how one might use this data to make decisions, specifically how to incorporate it into a mathematical model which can be used to make decisions.

Our aims are:

* To provide a central location for data relevant to include in and accelerate CSID modelling of malaria in the four frontline countries in the E8

* To catalyse CSID modelling calibrated to operationalisable datasets where the data characteristics and geographic context are well incorporated

* To establish a community of African modellers and analysts to support the tool

<h2>Core Values</h2> 

The development of the digital tool, the data to populate the tool and the development of the community of African modellers and analysts to use and maintain the tool will be founded on the following core values:

* Responsible use of data
* Scientific integrity
* Co-creation
* Openness
* Inclusivity


<h2>Guidelines for Data Inclusion</h2>

::: {.principles}

::: {layout-ncol=3}

::: {.principle}
### Accessible
Data showcased on Health RADAR is available and accessible to users already.
:::

::: {.principle}
### Befitting
A technical expert group audits the data to ensure it aligns with CSID modelling and excludes sensitive or potentially harmful information.
:::

::: {.principle}
### Cited
A suggested citation must be included so that the source and transformations of the data are adequately acknowledged. 
:::

::: {.principle}
### Documented 
The original data collection methods and the context in which the data may be correctly interpreted will be presented alongside the data to facilitate onward responsible use. 
:::

::: {.principle}
### Exemplified 
To catalyse the use of the data in CSID modelling, example code snippets will be provided to incorporate datasets into CSID models.  
:::


::: {.principle}
### Exemplified 2   <!-- this is added and hidden so that quarto can properly align the principles -->
To catalyse the use of the data in CSID modelling, example code snippets will be provided to incorporate datasets into CSID models.  
:::

:::

:::


## The Team

### The Modelling and Simulation Hub, Africa (MASHA)

The [Modelling and Simulation Hub, Africa (MASHA)](https://science.uct.ac.za/masha){.team-links} is a research group at the University of Cape Town. MASHA specialises in disease modelling for policy and capacity building of modellers across Africa and in LMIC. MASHA will support the project through developing and hosting the digital tool, facilitating and curating health and modelling data relevant to malaria transmission for inclusion in the digital tool and developing the code platform that incorporates the data into CSID models.

### Climate Systems Analysis Group (CSAG)

The [Climate Systems Analysis Group (CSAG)](https://www.csag.uct.ac.za){.team-links} at the University of Cape Town is a leading international climate research centre based in Africa with broad research skills and competency in both physical and social dimensions of climate, strong experience in engaging with society, and an excellent track record in capacity development. CSAG will support the project by facilitating and curating climate data relevant to malaria transmission for inclusion in the digital tool.

### Clinton Health Access Initiative (CHAI)

The [Clinton Health Access Initiative (CHAI)](https://www.clintonhealthaccess.org){.team-links} is a non-profit organisation that operates at the nexus of business, government and health to save lives and reduce disease. CHAI works with national governments to reform their health systems, targeting areas where current approaches are failing or moving too slowly. CHAI will support the project by facilitating and curating health system data and malaria intervention costs for inclusion in the digital tool.

### SAMRC Office of Malaria Research (MOMR)

The [Office of Malaria Research (MOMR)](https://www.samrc.ac.za/research/centre-and-platforms-office/malaria-research-group){.team-links} in the South African Medical Research Council
(SAMRC) funds and facilitates research to understand the social and biological impact of the
disease and to develop malaria control programmes. MOMR will support the project by
facilitating and curating entomological data and data related to vector intervention impact
into the digital tool.

:::





