---
title: "Contributing to Health RADAR"
subtitle: "Guidelines for effective contribution to the Health RADAR project"
page-layout: full
format: 
  html: 
    code-fold: false
title-block-banner: "#EDF3F9"
title-block-banner-color: "#212529"
comments: false
---

Thank you for choosing to contribute time to Health RADAR. 

Here are a few guidelines to help you understand the project, learn about the style guide, development best practices and how to contribute.

## Code of Conduct

This project and everyone participating in it is governed by our [Code of Conduct](https://github.com/healthradartool/.github/blob/main/CODE_OF_CONDUCT.md){target="_blank"}. By participating, you are expected to uphold this code.

## How can you contribute?

There are many ways in which the community can contribute to this project:

- Help develop pages for malaria data sources 
- Suggest datasources for inclusion
- Contribute to content editing
- Provide general feedback and suggestions

## Report issues

A great way to contribute is to report issues, either found when working on a pull request or when using Health RADAR. We have [issue templates](https://github.com/healthradartool/HealthRADAR/issues) to help you report feature requests or bugs. Please use these when reporting an issue. We also have a [report issues](/issues.qmd) page where you can report issues if you are not familiar with GitHub.

## Contributing a data source page

To contribute a data source page you will need to complete a page template and create a folder for any sample datasets and static images you have used. 

Each page has three major sections:

- Overview
- Visualisations
- Modelling

The overview section provides a brief overview of the dataset, including the source, how to access the data and any caveats or limitations to using the data. The visualisations section provides example plots of the data (such as temporal trends, geographic distributions or demographic breakdowns) to illustrate data characteristics. The modelling section provides worked code examples that demonstrate how to incorporate the dataset into climate-sensitive infectious disease models.

To learn more about contributing a data source page please look at our [contribution guide](https://github.com/healthradartool/.github/blob/main/CONTRIBUTING.md){target="_blank"}.


