on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2 

      - name: Install libcurl on Linux
        run: |
          sudo apt-get update -y && sudo apt-get install -y libcurl4-openssl-dev
          sudo apt-get install libharfbuzz-dev libfribidi-dev libfontconfig1-dev

      - name: Install sf dependencies on Linux
        run: |
          sudo apt-get install libudunits2-dev libgdal-dev
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libprotobuf-dev protobuf-compiler

      - name: Install protobuf
        run: |
          sudo apt-get update
          sudo apt-get install -y libprotobuf-dev protobuf-compiler libjq-dev jq

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      # From https://github.com/r-lib/actions/tree/v2-branch/setup-r
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      
      - name: Setup renv
        uses: r-lib/actions/setup-renv@v2

      - name: Render and Publish 
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: quarto-pub
          QUARTO_PUB_AUTH_TOKEN: ${{ secrets.QUARTO_PUB_AUTH_TOKEN }}
